name: Unit Test CI

on:
  workflow_dispatch:
  pull_request:
  push:
    paths:
      - .github/workflows/unit-tests.yaml
      - '**.java'
      - '**/pom.xml'

jobs:
  build:
    strategy:
      matrix:
        jdk: [ 11, 20 ]
        os: [ ubuntu-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.jdk }}
          distribution: temurin
          cache: maven
      - name: Compile and run tests (JDK 20)
        run: mvn -B package
        if: matrix.jdk == '20'
      - name: Compile and run tests (JDK 11)
        run: mvn -B -am -pl jvector-base test
        if: matrix.jdk == '11'
